[package]
name = "sauce-finder-rust"
version = "0.1.0"
authors = ["Rax Ixor <raxixor@rax.ee>"]
description = """It should be a Rust version of sauce-finder (located at https://gitlab.com/miicat/sauce-finder/)."""
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
async-trait = "0.1.30"
regex = "1.3"
serde = "1.0.106"
serde_json = "1.0"
colored = "1.9.3"
dialoguer = "0.6"
